//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCon.export
{
    using System;
    using System.Collections.Generic;
    
    public partial class ByteMeasurement
    {
        public int ID { get; set; }
        public int MeasurementID { get; set; }
        public System.DateTime Timestamp { get; set; }
        public byte Value { get; set; }
    }
}
