//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCon.export
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBModelContainer1 : DbContext
    {
        public DBModelContainer1()
            : base("name=DBModelContainer1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TargetName> TargetNameSet { get; set; }
        public virtual DbSet<Target> TargetSet { get; set; }
        public virtual DbSet<VariableEvent> VariableEventSet { get; set; }
    }
}
