//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetCon.export
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariableEvent
    {
        public long id { get; set; }
        public System.DateTime date { get; set; }
        public byte[] thresholdValue { get; set; }
        public byte[] thresholdValue2 { get; set; }
        public NetCon.util.ThresholdType thresholdType { get; set; }
        public NetCon.util.DataType thresholdDataType { get; set; }
    
        public virtual Target Target { get; set; }
    }
}
